### ISSUE TITLE
introduce version numbers

### ISSUE THREAD

**Issue by jakobj** [INM-6/python-dicthash#12]
since hashing is specifically sensitive to even small code changes we should start labeling commits that change the outcome of the hash function by release/version numbers.

**Comment by mschmidt87** [comment]
Do I understand you correctly that you want to modify the ` generate_hash_from_dict` function such that it always appends the current version number to the string that is being hashed in the end?

I think this is a good idea but I would restrict this to the release version number. Appending the current commit sounds quite complicated.

**Comment by jakobj** [comment]
No, I mean that we bump the version (in the `__version__` variable) and tag the commit with the new version whenever we introduce a change that requires us to edit the consistency check in the test suite. We could use the the bugfix position for this, i.e., bump from `1.0.0` to `1.0.1` if the hash changes. I don't want to encode the version number/commit id directly into the hash.

**Comment by mschmidt87** [comment]
Ah I see, yes that is a good idea. We should start doing this. And by the way, we have to update the example in the documentation of  `generate_hash_from_dict`. The given hash is definitely outdated.
