### ISSUE TITLE
Use setuptools and generate proper documentation

### ISSUE THREAD

**Issue by mschmidt87** [INM-6/python-dicthash#23]
In preparation of a release on pypi, we have to add the necessary infrastructure using `setuptools`.
In addition, we should add proper documentation and publish it on readthedocs.org .

**Comment by mschmidt87** [comment]
Turns out we already have setuptools integrated.
At the moment, we are using the MIT license for this package. In the h5py_wrapper, we are using GPL. Do we want to switch?

**Comment by mschmidt87** [comment]
@jakobj  Reminder.

**Comment by jakobj** [comment]
If it is a problem to release this under MIT while h5py_wrapper is under GPL, I am fine with changing to GPL. Would this make things easier?

**Comment by mschmidt87** [comment]
It seems that it's problematic to include GPL-licensed software in an MIT-licensed software.

[https://lukasa.co.uk/2012/05/GPL_vs_MIT_Which_License_To_Use/](https://lukasa.co.uk/2012/05/GPL_vs_MIT_Which_License_To_Use/) says:

> The secret is that really, it’s easy. If you want to prevent people from making changes to your work without providing them back to you, use the GPL. If you want people to use your name when they use your work in something, use MIT or BSD. If you honestly don’t care at all, use the WTFPL (the Do What The Fuck You Want To Public License). That’s the only decision you need to make.

So, if you use software that is licensed with GPL in your own library, then you have to use the GPL license, too. In other words, we have two options:

1.  Remove the test that uses the h5py_wrapper and use MIT license
2. Use GPL license

To decide whether to use 1 or 2, we have to answer the question: Do we want to allow other people to use python-dicthash in proprietary software?

**Comment by mschmidt87** [comment]
We decided to switch to GPLv2 license and implemented this with #34 .
