### ISSUE TITLE
Enable whitelist and blacklist to take keys in subdirectories

### ISSUE THREAD

**Issue by mschmidt87** [INM-6/python-dicthash#28]
Currently, the functionality of `whitelist` and `blacklist` is restricted to keys that appear on the top level of the given directionary. 

For instance, assuming we have the following the dictionary:
 ```
d = {'a': {'b': 1, 'c': 2},
      'd': 3}

```
we can only use `a, d` for `whitelist` and `blacklist` but not `b, c` because they appear in lower level (a subdirectory).

I propose to change the functionality such that one can specify keys in deeper structure by giving the full path to the key separated in a tuple of keys. For instance:
`dicthash.generate_hash_from_dict(d, blacklist=[('a', 'b')])` .

**Comment by jakobj** [comment]
closed by #29
