### ISSUE TITLE
dict and list can lead to same hash

### ISSUE THREAD

**Issue by jakobj** [INM-6/python-dicthash#6]
a dictionary and a list with the same content can lead to the same hash under particular circumstances:

``` python
d0 = {
    'a': ['b', 5],
}
d1 = {
    'a': {'b': 5},
}
```

will both lead to the same raw string `ab5` and hence produce the same hash. this could be fixed by inserting an `l` or `d` in front of the contents of the respective object (also applies for arrays/tuples etc.). ideas?

**Comment by mschmidt87** [comment]
I think, adding a prefix is a good idea. So this would then be:
dictionary: d
list: l
array: a
tuple: t
set: s

?

**Comment by jakobj** [comment]
hmm, i feel like we'd be back at the problem of needing `if isinstance`s. how about `d` for dict and `i` for iterable? but this would mean we can not distinguish between tuples, lists, arrays, etc.

**Comment by mschmidt87** [comment]
Yes, that's true. So, from my experience, it should not matter if the function cannot distinguish between tuples, lists, arrays etc., because the normal use case will be to use one particular type for a data entity, anyway. So, distinguishing between dictionaries and iterables should be fine.

**Comment by jakobj** [comment]
Seems like we reached an agreement, I'll implement that.
